### ISSUE TITLE
1.8

### ISSUE THREAD

**Issue by UntouchedOdin0** [Sauilitired/Hyperverse#1]
Will there be support for 1.8? I don't use 1.9+ because they aren't good.

**Comment by astei** [comment]
I'm an old cretin and _demand_ you add beta 1.7.3 support. Every version of Minecraft past beta 1.7.3 is awful.

**Comment by Proximyst** [comment]
I **need** this with a **custom** mod loader for infdev! I can't play with these new stupid blocks, it was the last good version...
