### ISSUE TITLE
Extra flags

### ISSUE THREAD

**Issue by Sauilitired** [Sauilitired/Hyperverse#15]
- auto-heal
- hunger
- alias
- entity spawning (toggle on and off)

**Comment by AeSix** [comment]
auto-heal and hunger are going into worldguard territory, imho not something that should be part of a world manager. 

alias for what?  If you mean to assign an alias to the worlds, that could be useful, for things like portals / teleport signs where the alias is used, but the alias could be defined to different worlds (say, "alias: nether; world: june_nether;" where in July, the nether is reset to "july_nether") (as a horrible example, but ya know. 

entity spawning imho should be per-world, defaulting to server setting if not explicitly set by the admin per world.
