### ISSUE TITLE
Way to disable safe teleport.

### ISSUE THREAD

**Issue by Orlaando-dev** [Sauilitired/Hyperverse#20]
**Is your feature request related to a problem? Please describe.**
The world spawn points I set are safe, however the plugin sometimes thinks they're unsafe. This is annoying as players will sometimes teleport to a point that isn't the intended spawn point upon switching worlds. From this, I believe a way to disable safe teleport would help with my issue.

**Describe the solution you'd like**
Perhaps a global config option, flag, whatever might be best to disable safe teleport.

**Describe alternatives you've considered**
I'm unable to think of any alternatives.

**Additional context**
None.

**Comment by Sauilitired** [comment]
Add `safe-teleport=false` to the Hyperverse configuration file.
