### ISSUE TITLE
[bug?][enhancement] Confusing command failure upon invalid feature setting

### ISSUE THREAD

**Issue by ZorudaRinku** [Sauilitired/Hyperverse#23]
**Describe the bug**
Creating a world has funky arguments

**To Reproduce**
Run Hyperverse in server

`hyperverse create minigames vanilla over_world 2148188269727541730 false flat`

[Hyperverse] Error: That is not a valid world type

Other world types I've tried: overworld, Overworld, over_world, OverWorld, the help command suggests "overworld" but that doesn't work. 

But when I run it like this

`hyperverse create minigames vanilla over_world`

It works fine but then I can't set the seed, generate structures, or the flatlands. 

**Expected behavior**
To create a world based on all arguments

**Screenshots**

**Server Version:**
- Paper version: git-Paper-224 (MC: 1.15.2) (Imple
menting API version 1.15.2-R0.1-SNAPSHOT)

**Additional context**
It seems the command works until you get to the seed variables, then you're unable to.

**Comment by Sauilitired** [comment]
I believe it would work if you used `/hyperverse create minigames vanilla over_world 2148188269727541730 false flatland`
instead, as `flat` is not a valid feature setup. This however means that the message is rather confusing, and should probably provide better feedback. That should definitely be improved, and more environment feature completions could be added as well.

**Comment by ZorudaRinku** [comment]
Yep that command worked so it looks like it's just the help command that was throwing me off. Thanks for your help!
