### ISSUE TITLE
[BUG] List of players in the world without formatting.

### ISSUE THREAD

**Issue by SrBedrock** [Sauilitired/Hyperverse#30]
**Describe the bug**
List of players in the worlds has no formatting.

**To Reproduce**
Use `/hvwho`

**Expected behavior**

Separate names with spaces and without receiving any color code from the previous nickname.

**Screenshots**

![image](https://user-images.githubusercontent.com/51332006/81984538-4e425c80-960b-11ea-958c-15446d41ae13.png)

**Server Version:**
- Tuinity version: git-Tuinity-20e7f28

**Comment by md5sha256** [comment]
Latest build should resolve this, however, I have yet to test this with more than 2 players on the server.

**Comment by SrBedrock** [comment]
Solved!

![image](https://user-images.githubusercontent.com/51332006/82079249-e9ddd680-96b8-11ea-9ba1-956059204533.png)
