### ISSUE TITLE
Respawn players at bed

### ISSUE THREAD

**Issue by xoltiv** [Sauilitired/Hyperverse#31]
**Is your feature request related to a problem? Please describe.**
Players respawn at the world spawn instead of their beds when they die.

**Describe the solution you'd like**
When the local-respawn flag is enabled for a world, respawn the player at the last bed they slept in in that world.  When a respawn-world is provided, respawn the player at their bed in the given world.

**Describe alternatives you've considered**
This feature is available in Multiverse.

**Comment by Sauilitired** [comment]
The problem with this is that beds are not stored per-world, but rather per player. We could circumvent this by storing our own bed spawns, but this is already offered when using the per-world player data.

I can check if we can repurpose some of the persistent location stuff to keep track of bed spawns, but it's not going to be super pretty.

**Comment by Sauilitired** [comment]
Okay, I ended up extending our location persistence system. It will store your bed locations when you sleep and use those as long as `local-respawn` or `respawn-world` are set.

I'll also add a `force-spawn` flag, which forces you to respawn at the world spawn location no matter what, ignoring bed respawns. 

I hope this will provide enough functionality.
