### ISSUE TITLE
[BUG] Players must sleep through the night to set bed spawn

### ISSUE THREAD

**Issue by xoltiv** [Sauilitired/Hyperverse#32]
**Describe the bug**
Players cannot set their bed spawn by clicking the bed during the day.  The "Respawn point set" message is sent, but the respawn point isn't updated.  It only works when the player sleeps through the night.

**To Reproduce**
1. Place bed and right-click it during the day
2. Die

**Expected behavior**
When the player clicks the bed during the day, the respawn point is updated.

**Comment by Sauilitired** [comment]
Isn't this vanilla behaviour, or am I getting that wrong?

**Comment by xoltiv** [comment]
Default bed spawning rules are [here](https://minecraft.gamepedia.com/Bed) under the section "Setting the spawn point"

**Comment by Sauilitired** [comment]
I've attempted to fix this and I hope it works like expected now. There's a tiny problem in just matching the vanilla code, in that the update message is only sent if the location stored in the player data is updated, and this causes problems with the per-player data system.

It currently updates the bed spawn location whenever a bed is used that is not in the nether, the player isn't too far away or some other problem occurred. 

So, most of the time when you right click a bed, it'll record this location. This should be closer to vanilla behaviour, at least. 

If this remains a problem, please update the issue and thanks for reporting this in the first place =)
