### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by josefdebnar7** [Sauilitired/Hyperverse#8]
**Describe the bug**
Install Hypeverse (build 59 - 60),
Big error will appear, because of missing storage.db file in plugin folder. Plugin won't work.

**To Reproduce**
Clean install of Hypeverse

**Expected behavior**
Create storage.db automatically

**Screenshots**

**Server Version:**
- Paper version: git-Paper-205 (MC: 1.15.2)

**Additional context**
If you create file "storage.db" plugin will solve this problem by itself.

**Comment by Sauilitired** [comment]
Thanks. Turns out the plugin's data folder wasn't created properly, and this meant that Java couldn't create the files inside of that folder.

**Comment by josefdebnar7** [comment]
Fixed with https://github.com/Sauilitired/Hyperverse/commit/c45a64a5a70254ae7a471b3590c5cb56fdbc2007
Working fine from build 61 and up.
