### ISSUE TITLE
World importing

### ISSUE THREAD

**Issue by josefdebnar7** [Sauilitired/Hyperverse#9]
**Is your feature request related to a problem? Please describe.**
A little. Possibilites to import and load worlds witch are not created in HV is very important.

**Describe the solution you'd like**
Just import world from world container folder on command /hv import <name> [options]
(auto-import won't work)

**Describe alternatives you've considered**
Re-create world with /hv create <name> ..., but thats little bit awkward solution.

**Additional context**

(paper 205, hv 63)

**Comment by Sauilitired** [comment]
This has been added in recent development builds. `/hv import <world name> <generator>`. I hope this works. 

A future addition will be the option to import entire multiverse configurations as well, for people looking to migrate.
